### ISSUE TITLE
share based access token

### ISSUE THREAD

**Issue by nishith107** [delta-io/delta-sharing#245]
Currently bearer token specified in the config files would access to all shares specified in the files which would defeat the purpose of access control in giving the granular access to each share.

I can see that this Databricks Delta sharing has this feature to associate share with receipent.

Any plans to incorporate that feature here as well  ?

**Comment by linzhou-db** [comment]
Thanks! So the oss server is a reference server, feel free send out PRs or update locally to add those features.

**Comment by fizix137** [comment]
We have to implement a stand-alone Delta Sharing Server because I am working in the Azure Government version of Databricks which doesn't have Unity Catalog. I noticed in the API description yaml has two servers:

```
servers:
  - url: 'http://localhost:8000/api/v1'
    description: Local dev server (APIv1)
  - url: 'https://sharing.delta.io/delta-sharing/'
    description: 'Demo Delta Sharing server'
```
Do we have to create our own `Local dev server` or build it separately?  Just need to know before I put the work in.

Is this the *oss server* @linzhou-db refers to?
